### ISSUE TITLE
List of upcoming Events

### ISSUE THREAD

**Issue by Gracey46** [Gracey46/Project-Planning#1]
**User story:**
As a local resident, I want to see a list of upcoming local events so that I can find interesting events to attend.

**Assessment Criteria:** 

- [ ] The home page displays a list of upcoming community events. 
- [ ] Each event listing displays event's name, time, date, and a brief description.
- [ ] The list looks responsive and good on all main response sites. 

**Tasks:**

- [ ] Add an HTML section on the home page dedicated to upcoming community events.
- [ ] Style the event using bootstrap.
- [ ] Add some simple events including event name, date, time, and a brief description.
